[whitelist]
users = ["da3bd8cdf6412e705d89b9c83c0c87064512696a"]

[database]
directory = "./local-storage"
secondary = "./local-secondary-storage"

[p2p]
listen_on = ["/ip4/0.0.0.0/udp/8000/quic-v1", "/ip4/0.0.0.0/tcp/8000"]
