[workspace]
resolver = "2"

members = ["block-builder", "computer", "da", "sequencer", "verifier"]

[workspace.package]
version = "0.0.1"
authors = [
    "Eugene Kim <ek@karma3labs.com>",
    "Filip Lazović <filip@karma3labs.com>",
]
edition = "2021"
