[workspace]
resolver = "2"

members = ["block-builder", "computer", "da", "sequencer", "verifier"]

[workspace.package]
version = "0.0.1"
authors = [
    "Eugene Kim <ek@karma3labs.com>",
    "Filip Lazović <filip@karma3labs.com>",
]
edition = "2021"

[workspace.dependencies]
libp2p = "0.53.2"
futures = "0.3.30"
tokio = { version = "1.38", default-features = false }
tracing = "0.1.37"
tracing-subscriber = "0.3"
