
services:
  sequencer:
    build:
      context: .
      dockerfile: sequencer/Dockerfile
    container_name: sequencer
    environment:
      - INSTANCE_NAME=sequencer
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - openrank-network
  block-builder:
    build:
      context: .
      dockerfile: block-builder/Dockerfile
    container_name: block-builder
    environment:
      - INSTANCE_NAME=block-builder
      - PORT=9000
    ports:
      - "9000:9000"
    networks:
      - openrank-network

  verifier-1:
    build:
      context: .
      dockerfile: verifier/Dockerfile
    container_name: verifier-1
    environment:
      - INSTANCE_NAME=verifier-1
      - PORT=11001
    ports:
      - "11001:11001"
    networks:
      - openrank-network

  verifier-2:
    build:
      context: .
      dockerfile: verifier/Dockerfile
    container_name: verifier-2
    environment:
      - INSTANCE_NAME=verifier-2
      - PORT=11002
    ports:
      - "11002:11002"
    networks:
      - openrank-network

  verifier-3:
    build:
      context: .
      dockerfile: verifier/Dockerfile
    container_name: verifier-3
    environment:
      - INSTANCE_NAME=verifier-3
      - PORT=11003
    ports:
      - "11003:11003"
    networks:
      - openrank-network

  computer:
    build:
      context: .
      dockerfile: computer/Dockerfile
    container_name: computer
    environment:
      - INSTANCE_NAME=computer
      - PORT=10000
    ports:
      - "10000:10000"
    networks:
      - openrank-network

networks:
    openrank-network:
        driver: bridge
