[package]
name = "smart-contract-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy = { version = "0.3", features = ["full", "node-bindings"] }
eyre = "0.6.12"
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }

openrank-common = { path = "../common" }
alloy-rlp = "0.3.8"
