[whitelist]
contract_address = "7c2df8c780d2e0401d7091c54086d228dabad208"
rpc_url = "https://eth.merkle.io/"
mnemonic = "work man father plunge mystery proud hollow address reunion sauce theory bonus"
