[package]
name = "openrank-common"
description = "Common library for OpenRank codebase"
license = "MIT"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
hex = { workspace = true }
