[package]
name = "openrank-block-builder"
description = "OpenRank - Block Builder Node"
license = "MIT"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
